In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [66]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 9CB9-E181

 Directory of C:\Mod5-Statistics\corelation

11/04/2023  03:43 PM    <DIR>          .
11/04/2023  03:43 PM    <DIR>          ..
11/03/2023  10:00 PM    <DIR>          .ipynb_checkpoints
11/04/2023  12:11 PM           540,200 amazon_laptop_prices_v01.csv
10/26/2023  10:39 AM             3,301 car_crashes.csv
11/04/2023  03:43 PM           149,684 CORRELATION.ipynb
10/16/2023  10:53 AM         2,435,302 GlobalWeatherRepository.csv.xls
11/04/2023  12:05 PM         1,423,529 housing.csv
10/19/2023  09:43 AM           453,248 shopping_trends.csv
10/19/2023  09:43 AM           416,614 shopping_trends_updated.csv
10/26/2023  10:39 AM             9,729 tips.csv
10/26/2023  10:39 AM            57,018 titanic.csv
               9 File(s)      5,488,625 bytes
               3 Dir(s)  41,171,599,360 bytes free

### TIPS

In [3]:
tips=pd.read_csv("tips.csv")

In [4]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [7]:
tips_cor = tips.corr()
tips_cor

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [8]:
tips_cor["total_bill"].sort_values(ascending=False)

total_bill    1.000000
tip           0.675734
size          0.598315
Name: total_bill, dtype: float64

   **from tips dataset correlation:**
   
       * tips and total bill is more related to the data,showing +ve correlation.That is when total bill increases tip also increases(in a big strength)
        * size and tips is also related , but not much as total bill,size is showing +ve relation to total bill(not in a big strength)
        *that is tips,size and total bill have correlation between them

### TITANIC

In [9]:
titanic=pd.read_csv("titanic.csv")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [10]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [11]:
titanic_cor = titanic.corr()
titanic_cor

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
survived,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307,-0.557080,-0.203367
pclass,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500,0.094035,0.135207
age,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067,0.280328,0.198270
sibsp,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651,-0.253586,-0.584471
parch,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225,-0.349943,-0.583398
fare,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000,-0.182024,-0.271832
adult_male,-0.557080,0.094035,0.280328,-0.253586,-0.349943,-0.182024,1.000000,0.404744
alone,-0.203367,0.135207,0.198270,-0.584471,-0.583398,-0.271832,0.404744,1.000000

In [12]:
titanic_cor["survived"].sort_values(ascending=False)

survived      1.000000
fare          0.257307
parch         0.081629
sibsp        -0.035322
age          -0.077221
alone        -0.203367
pclass       -0.338481
adult_male   -0.557080
Name: survived, dtype: float64

   **from titanic dataset correlation:**
   
       survived show that:
* survived, fare,parch shows +ve correlation.
* sibsp,age,alone,pclass,adult_male shows -ve correlation.
* fare is showing a very small +ve relation when the fare increase the class increase which result in the rescue faste
* showing negative relation towards male which indicates survival rate decreased in male which indicates there are chances male taking part in rescue operation risking their own lives

In [14]:
titanic_cor["pclass"].sort_values(ascending=False)

pclass        1.000000
alone         0.135207
adult_male    0.094035
sibsp         0.083081
parch         0.018443
survived     -0.338481
age          -0.369226
fare         -0.549500
Name: pclass, dtype: float64

**from titanic dataset correlation:**

    pclass show
        * alone,adult_male,sibsp,parch have +ve correlation with pclass
        *survived,age,fare have -ve correlation with pclass

In [15]:
titanic_cor["age"].sort_values(ascending=False)

age           1.000000
adult_male    0.280328
alone         0.198270
fare          0.096067
survived     -0.077221
parch        -0.189119
sibsp        -0.308247
pclass       -0.369226
Name: age, dtype: float64

**from titanic dataset correlation:**

    age show
        * alone,adult_male,fare have +ve correlation with age
        *survived,pclass,sibsp,parch have -ve correlation with age

In [17]:
titanic_cor["sibsp"].sort_values(ascending=False)

sibsp         1.000000
parch         0.414838
fare          0.159651
pclass        0.083081
survived     -0.035322
adult_male   -0.253586
age          -0.308247
alone        -0.584471
Name: sibsp, dtype: float64

**from titanic dataset correlation:**

    sibsp show
        * parch,fare,pclass, have +ve correlation with sibsp
        *survived,adult_male,age,alone have -ve correlation with sibsp
        * if the person is alone there is no chance for sibsp

In [18]:
titanic_cor["parch"].sort_values(ascending=False)

parch         1.000000
sibsp         0.414838
fare          0.216225
survived      0.081629
pclass        0.018443
age          -0.189119
adult_male   -0.349943
alone        -0.583398
Name: parch, dtype: float64

**from titanic dataset correlation:**

    parch show
        * sibsp,fare,survived,pclass have +ve correlation with parch
        *  showing +ve relation to sibsp which means parent or children or family present
        * age,adult_male,alone have -ve correlation with parch
        * showing -ve relation to alone , if the person is alone parent or children wont travel with them

In [19]:
titanic_cor["fare"].sort_values(ascending=False)

fare          1.000000
survived      0.257307
parch         0.216225
sibsp         0.159651
age           0.096067
adult_male   -0.182024
alone        -0.271832
pclass       -0.549500
Name: fare, dtype: float64

**from titanic dataset correlation:**

    fare show
        *survived,parch,sibsp,age have +ve correlation with fare
        *adul_male,alone,pclass have -ve correlation with fare

In [20]:
titanic_cor["adult_male"].sort_values(ascending=False)

adult_male    1.000000
alone         0.404744
age           0.280328
pclass        0.094035
fare         -0.182024
sibsp        -0.253586
parch        -0.349943
survived     -0.557080
Name: adult_male, dtype: float64

**from titanic dataset correlation:**

    adult_male show
        * alone,age,pclass have +ve correlation with adult_male
        * fare,sibsp,parch,survived have -ve correlation with adult_male

In [21]:
titanic_cor["alone"].sort_values(ascending=False)

alone         1.000000
adult_male    0.404744
age           0.198270
pclass        0.135207
survived     -0.203367
fare         -0.271832
parch        -0.583398
sibsp        -0.584471
Name: alone, dtype: float64

**from titanic dataset correlation:**

    alone show
        * adult_male,age,pclass have +ve correlation with alone
        * survived,fare,parch,sibsp have -ve correlation with alone
        *if the person is alone parent/children ,sibling/spouse wont travel with them

### HOUSING

In [45]:
housing=pd.read_csv("housing.csv")
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [46]:
housing_cor=housing.corr()
housing_cor

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,1.000000,-0.924664,-0.108197,0.044568,0.069608,0.099773,0.055310,-0.015176,-0.045967
latitude,-0.924664,1.000000,0.011173,-0.036100,-0.066983,-0.108785,-0.071035,-0.079809,-0.144160
housing_median_age,-0.108197,0.011173,1.000000,-0.361262,-0.320451,-0.296244,-0.302916,-0.119034,0.105623
total_rooms,0.044568,-0.036100,-0.361262,1.000000,0.930380,0.857126,0.918484,0.198050,0.134153
total_bedrooms,0.069608,-0.066983,-0.320451,0.930380,1.000000,0.877747,0.979728,-0.007723,0.049686
population,0.099773,-0.108785,-0.296244,0.857126,0.877747,1.000000,0.907222,0.004834,-0.024650
households,0.055310,-0.071035,-0.302916,0.918484,0.979728,0.907222,1.000000,0.013033,0.065843
median_income,-0.015176,-0.079809,-0.119034,0.198050,-0.007723,0.004834,0.013033,1.000000,0.688075
median_house_value,-0.045967,-0.144160,0.105623,0.134153,0.049686,-0.024650,0.065843,0.688075,1.000000

In [48]:
housing_cor["longitude"].sort_values(ascending=False)

longitude             1.000000
population            0.099773
total_bedrooms        0.069608
households            0.055310
total_rooms           0.044568
median_income        -0.015176
median_house_value   -0.045967
housing_median_age   -0.108197
latitude             -0.924664
Name: longitude, dtype: float64

   **from housing dataset**
   
            longitude shows:
    * longitude is showing high negative correlation with latitude which means when latitude increases longitude decreases and vice versa
    * population,total_bedrooms,households,total_rooms  are showing correlation as the values are more close to 0

In [49]:
housing_cor["latitude"].sort_values(ascending=False)

latitude              1.000000
housing_median_age    0.011173
total_rooms          -0.036100
total_bedrooms       -0.066983
households           -0.071035
median_income        -0.079809
population           -0.108785
median_house_value   -0.144160
longitude            -0.924664
Name: latitude, dtype: float64

   **from housing dataset**
   
            latitude shows:
    * latitude is showing negative correlation with total_rooms,total_bedrooms,households, population,median_house_value,longitude
    * housing_median_age have less +ve correlation as the values are more close to 0
    *showing big-ve relation to longitude

In [52]:
housing_cor["population"].sort_values(ascending=False)

population            1.000000
households            0.907222
total_bedrooms        0.877747
total_rooms           0.857126
longitude             0.099773
median_income         0.004834
median_house_value   -0.024650
latitude             -0.108785
housing_median_age   -0.296244
Name: population, dtype: float64

   **from housing dataset**
   
            population shows:
    * households,total_bedrooms,total_rooms,longitude,median_income have less +ve correlation( as population increases demands for household also increase)
    * median_house_value,latitude,housing_median_age have small -ve correlation (age increases population decreases )

In [53]:
housing_cor["total_bedrooms"].sort_values(ascending=False)

total_bedrooms        1.000000
households            0.979728
total_rooms           0.930380
population            0.877747
longitude             0.069608
median_house_value    0.049686
median_income        -0.007723
latitude             -0.066983
housing_median_age   -0.320451
Name: total_bedrooms, dtype: float64

   **from housing dataset**
   
            total_bedrooms shows:
    * total_bedroom showing high +ve correlation to total_rooms and households( as total bedroom increases the house hold needs as well as the number of rooms increases)
    * population,longitude,median_house_value also have +ve correlation
    *median_income,latitude,housing_median_age have less -ve correlation

In [54]:
housing_cor["housing_median_age"].sort_values(ascending=False)

housing_median_age    1.000000
median_house_value    0.105623
latitude              0.011173
longitude            -0.108197
median_income        -0.119034
population           -0.296244
households           -0.302916
total_bedrooms       -0.320451
total_rooms          -0.361262
Name: housing_median_age, dtype: float64

   **from housing dataset**
   
            housing_median_age shows:
    * housing_median_age is showing +ve correlation with median_house_value,latitude
    * housing_median_age have less -ve correlation  with longitude,median_income,population ,households,total_bedrooms,total_rooms

In [55]:
housing_cor["total_rooms"].sort_values(ascending=False)

total_rooms           1.000000
total_bedrooms        0.930380
households            0.918484
population            0.857126
median_income         0.198050
median_house_value    0.134153
longitude             0.044568
latitude             -0.036100
housing_median_age   -0.361262
Name: total_rooms, dtype: float64

   **from housing dataset**
   
            total_rooms shows:
    * total_bedrooms,households,population,median_income,median_house_value,longitude have +ve correlation 
    * latitude,housing_median_age have -ve correlation

In [59]:
housing_cor["households"].sort_values(ascending=False)

households            1.000000
total_bedrooms        0.979728
total_rooms           0.918484
population            0.907222
median_house_value    0.065843
longitude             0.055310
median_income         0.013033
latitude             -0.071035
housing_median_age   -0.302916
Name: households, dtype: float64

   **from housing dataset**
   
            households shows:
    * total_bedrooms,total_rooms,population,median_house_value,longitude,median_income have +ve correlation 
    * latitude,housing_median_age have -ve correlation

In [60]:
housing_cor["median_house_value"].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

   **from housing dataset**
   
           median_house_value shows:
    * showing +ve relation to income which shows the income increase result in the increased house value also
    * total_rooms,housing_median_age,households,total_bedrooms have +ve correlation 
    * population,longitude,latitude have -ve correlation

In [58]:
housing_cor["median_income"].sort_values(ascending=False)

median_income         1.000000
median_house_value    0.688075
total_rooms           0.198050
households            0.013033
population            0.004834
total_bedrooms       -0.007723
longitude            -0.015176
latitude             -0.079809
housing_median_age   -0.119034
Name: median_income, dtype: float64

   **from housing dataset**
   
            median_income shows:
    * median_house_value,total_rooms,total_rooms,population have +ve correlation 
    * total_bedrooms,longitude,latitude,housing_median_age have -ve correlation

### CAR CRASHES

In [22]:
car_crashes = pd.read_csv("car_crashes.csv")
car_crashes

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA
5,13.6,5.032,3.808,10.744,12.920,835.50,139.91,CO
6,10.8,4.968,3.888,9.396,8.856,1068.73,167.02,CT
7,16.2,6.156,4.860,14.094,16.038,1137.87,151.48,DE
8,5.9,2.006,1.593,5.900,5.900,1273.89,136.05,DC
9,17.9,3.759,5.191,16.468,16.826,1160.13,144.18,FL
10,15.6,2.964,3.900,14.820,14.508,913.15,142.80,GA
11,17.5,9.450,7.175,14.350,15.225,861.18,120.92,HI
12,15.3,5.508,4.437,13.005,14.994,641.96,82.75,ID
13,12.8,4.608,4.352,12.032,12.288,803.11,139.15,IL
14,14.5,3.625,4.205,13.775,13.775,710.46,108.92,IN
15,15.7,2.669,3.925,15.229,13.659,649.06,114.47,IA
16,17.8,4.806,4.272,13.706,15.130,780.45,133.80,KS
17,21.4,4.066,4.922,16.692,16.264,872.51,137.13,KY
18,20.5,7.175,6.765,14.965,20.090,1281.55,194.78,LA
19,15.1,5.738,4.530,13.137,12.684,661.88,96.57,ME
20,12.5,4.250,4.000,8.875,12.375,1048.78,192.70,MD
21,8.2,1.886,2.870,7.134,6.560,1011.14,135.63,MA
22,14.1,3.384,3.948,13.395,10.857,1110.61,152.26,MI
23,9.6,2.208,2.784,8.448,8.448,777.18,133.35,MN
24,17.6,2.640,5.456,1.760,17.600,896.07,155.77,MS
25,16.1,6.923,5.474,14.812,13.524,790.32,144.45,MO
26,21.4,8.346,9.416,17.976,18.190,816.21,85.15,MT
27,14.9,1.937,5.215,13.857,13.410,732.28,114.82,NE
28,14.7,5.439,4.704,13.965,14.553,1029.87,138.71,NV
29,11.6,4.060,3.480,10.092,9.628,746.54,120.21,NH
30,11.2,1.792,3.136,9.632,8.736,1301.52,159.85,NJ
31,18.4,3.496,4.968,12.328,18.032,869.85,120.75,NM
32,12.3,3.936,3.567,10.824,9.840,1234.31,150.01,NY
33,16.8,6.552,5.208,15.792,13.608,708.24,127.82,NC
34,23.9,5.497,10.038,23.661,20.554,688.75,109.72,ND
35,14.1,3.948,4.794,13.959,11.562,697.73,133.52,OH
36,19.9,6.368,5.771,18.308,18.706,881.51,178.86,OK
37,12.8,4.224,3.328,8.576,11.520,804.71,104.61,OR
38,18.2,9.100,5.642,17.472,16.016,905.99,153.86,PA
39,11.1,3.774,4.218,10.212,8.769,1148.99,148.58,RI
40,23.9,9.082,9.799,22.944,19.359,858.97,116.29,SC
41,19.4,6.014,6.402,19.012,16.684,669.31,96.87,SD
42,19.5,4.095,5.655,15.990,15.795,767.91,155.57,TN
43,19.4,7.760,7.372,17.654,16.878,1004.75,156.83,TX
44,11.3,4.859,1.808,9.944,10.848,809.38,109.48,UT
45,13.6,4.080,4.080,13.056,12.920,716.20,109.61,VT
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY

In [34]:
car_crashes.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [23]:
carcrashes_cor = car_crashes.corr()
carcrashes_cor

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
total,1.000000,0.611548,0.852613,0.827560,0.956179,-0.199702,-0.036011
speeding,0.611548,1.000000,0.669719,0.588010,0.571976,-0.077675,-0.065928
alcohol,0.852613,0.669719,1.000000,0.732816,0.783520,-0.170612,-0.112547
not_distracted,0.827560,0.588010,0.732816,1.000000,0.747307,-0.174856,-0.075970
no_previous,0.956179,0.571976,0.783520,0.747307,1.000000,-0.156895,-0.006359
ins_premium,-0.199702,-0.077675,-0.170612,-0.174856,-0.156895,1.000000,0.623116
ins_losses,-0.036011,-0.065928,-0.112547,-0.075970,-0.006359,0.623116,1.000000

In [27]:
carcrashes_cor["total"].sort_values(ascending=False)

total             1.000000
no_previous       0.956179
alcohol           0.852613
not_distracted    0.827560
speeding          0.611548
ins_losses       -0.036011
ins_premium      -0.199702
Name: total, dtype: float64

   **from car_crases dataset**
   
       total shows:
           * no_previous have maximum +ve correlation(strength is more)
           * alcohol also have +ve correlation,that is when alcohol consumption increases car crash also increases
           * not distracted also have +ve corelation,that is when the driver is not distracted opposite people/car can be a reason for car crash)
           * speeding is showing positive corelation but the strength is less compared to the above ones,that is when the speed increase car_crash also increases
           * ins losses ans ins premium have less -ve  correlation

In [28]:
carcrashes_cor["speeding"].sort_values(ascending=False)

speeding          1.000000
alcohol           0.669719
total             0.611548
not_distracted    0.588010
no_previous       0.571976
ins_losses       -0.065928
ins_premium      -0.077675
Name: speeding, dtype: float64

   **from car_crases dataset**
   
       speeding shows:
           * alcohol also high +ve correlation,that is when alcohol consumption increases car crash also increases
           * total is showing positive corelation after alcohol
           * not distracted also have +ve corelation,that is when the driver is not distracted opposite people/car can be a reason for car crash)
           * no_previous have minimum +ve correlation
           * ins losses ans ins premium have less -ve  correlation

In [35]:
carcrashes_cor["alcohol"].sort_values(ascending=False)

alcohol           1.000000
total             0.852613
no_previous       0.783520
not_distracted    0.732816
speeding          0.669719
ins_losses       -0.112547
ins_premium      -0.170612
Name: alcohol, dtype: float64

   **from car_crases dataset**
   
       alcohol shows:
           * alcohol is having high correlation with total
           * no_previous have +ve correlation after total
           * not distracted also have +ve corelation,that is when the driver is not distracted opposite people/car can be a reason for car crash)
           * speeding is showing positive corelation but the strength is less compared to the above ones,that is when the speed increase car_crash also increases
           * ins losses ans ins premium have less -ve  correlation

In [30]:
carcrashes_cor["not_distracted"].sort_values(ascending=False)

not_distracted    1.000000
total             0.827560
no_previous       0.747307
alcohol           0.732816
speeding          0.588010
ins_losses       -0.075970
ins_premium      -0.174856
Name: not_distracted, dtype: float64

   **from car_crases dataset**
   
       not distracted shows:
           * not distracted having high correlation with total
           * no_previous have +ve correlation after total
           * alcohol also high +ve correlation,that is when alcohol consumption increases car crash also increases
           * speeding is showing positive corelation but the strength is less compared to the above ones,that is when the speed increase car_crash also increases
           * ins losses ans ins premium have less -ve  correlation

In [31]:
carcrashes_cor["no_previous"].sort_values(ascending=False)

no_previous       1.000000
total             0.956179
alcohol           0.783520
not_distracted    0.747307
speeding          0.571976
ins_losses       -0.006359
ins_premium      -0.156895
Name: no_previous, dtype: float64

   **from car_crases dataset**
   
       no_previous shows:
            * no previous having high correlation with total
            * alcohol also high +ve correlation,that is when alcohol consumption increases car crash also increases
            * not distracted also have +ve corelation,that is when the driver is not distracted opposite people/car can be a reason for car crash)
            * speeding is showing positive corelation but the strength is less compared to the above ones,that is when the speed increase car_crash also increases
            * ins losses ans ins premium have less -ve  correlation

In [32]:
carcrashes_cor["ins_premium"].sort_values(ascending=False)

ins_premium       1.000000
ins_losses        0.623116
speeding         -0.077675
no_previous      -0.156895
alcohol          -0.170612
not_distracted   -0.174856
total            -0.199702
Name: ins_premium, dtype: float64

   **from car_crases dataset**
   
        ins premium shows:
           * ins losses have maximum +ve correlation(strength is more)
           * speeding,no previous,alcohol,not distracted,total have -ve  correlation

In [33]:
carcrashes_cor["ins_losses"].sort_values(ascending=False)

ins_losses        1.000000
ins_premium       0.623116
no_previous      -0.006359
total            -0.036011
speeding         -0.065928
not_distracted   -0.075970
alcohol          -0.112547
Name: ins_losses, dtype: float64

     **from car_crases dataset**
   
        ins losses shows:
           * ins premium have maximum +ve correlation(strength is more)
           * speeding,no previous,alcohol,not distracted,total have -ve  correlation

### TRENDS

In [36]:
trends = pd.read_csv("shopping_trends.csv",index_col=0)
trends

,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
Customer ID,,,,,,,,,,,,,,,,,,
1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [37]:
trends.columns

Index(['Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)',
       'Location', 'Size', 'Color', 'Season', 'Review Rating',
       'Subscription Status', 'Payment Method', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Preferred Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [38]:
trends_corr=trends.corr()
trends_corr

,Age,Purchase Amount (USD),Review Rating,Previous Purchases
Age,1.000000,-0.010424,-0.021949,0.040445
Purchase Amount (USD),-0.010424,1.000000,0.030776,0.008063
Review Rating,-0.021949,0.030776,1.000000,0.004229
Previous Purchases,0.040445,0.008063,0.004229,1.000000

In [39]:
trends_corr["Age"].sort_values(ascending=False)

Age                      1.000000
Previous Purchases       0.040445
Purchase Amount (USD)   -0.010424
Review Rating           -0.021949
Name: Age, dtype: float64

**from trends dataset**

    Age shows:
       * none of the points are showing correlation as the values are more close to 0

In [40]:
trends_corr["Purchase Amount (USD)"].sort_values(ascending=False)

Purchase Amount (USD)    1.000000
Review Rating            0.030776
Previous Purchases       0.008063
Age                     -0.010424
Name: Purchase Amount (USD), dtype: float64

**from trends dataset**

    Purchase Amount (USD) shows:
       * none of the points are showing correlation as the values are more close to 0

In [41]:
trends_corr["Review Rating"].sort_values(ascending=False)

Review Rating            1.000000
Purchase Amount (USD)    0.030776
Previous Purchases       0.004229
Age                     -0.021949
Name: Review Rating, dtype: float64

**from trends dataset**

    Review Rating shows:
       * none of the points are showing correlation as the values are more close to 0

In [42]:
trends_corr["Previous Purchases"].sort_values(ascending=False)

Previous Purchases       1.000000
Age                      0.040445
Purchase Amount (USD)    0.008063
Review Rating            0.004229
Name: Previous Purchases, dtype: float64

**from trends dataset**

    Previous Purchases shows:
       * none of the points are showing correlation as the values are more close to 0

### LAPTOP

In [61]:
laptop = pd.read_csv("amazon_laptop_prices_v01.csv",index_col=0)
laptop

,model,screen_size,color,harddisk,cpu,ram,OS,special_features,graphics,graphics_coprocessor,cpu_speed,rating,price
brand,,,,,,,,,,,,,
ROKC,NaN,14 Inches,Blue,1000 GB,Intel Core i7,8 GB,Windows 11,NaN,Integrated,Intel,1.2 GHz,NaN,$589.99
HP,NaN,15.6 Inches,Silver,1000 GB,Intel Core i5,64 GB,Windows 11 Pro,Backlit Keyboard,Integrated,Intel,NaN,4.5,$999.99
MSI,Vector GP66 12UGS-267,15.66 Inches,Core Black,NaN,Intel Core i9,32 GB,Windows 11 Home,NaN,Dedicated,NaN,1.8 GHz,5.0,"$1,599.00"
Apple,MacBook Air,13.3 Inches,Silver,256 GB,Unknown,8 GB,Mac OS,Backlit Keyboard,Integrated,NaN,NaN,4.8,$689.99
Apple,MacBook Air,15.3 Inches,Midnight,256 GB,Unknown,8 GB,Mac OS,NaN,Integrated,NaN,NaN,4.8,"$1,144.48"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSI,Stealth GS66 12UGS-025,15.6 Inches,Core Black,NaN,Intel Core i9,32 GB,Windows 11 Home,NaN,Dedicated,NVIDIA GeForce RTX 3070,1.8 GHz,1.0,"$1,699.00"
ROKC,NaN,14 Inches,Blue,1000 GB,Intel Core i7,8 GB,Windows 11,NaN,Integrated,Intel,1.2 GHz,NaN,$589.99
Dell,Inspiron 3511 Laptop,15.6 Inches,Black,512 GB,Core i3,8 GB,Windows 10 Home,Wifi & Bluetooth,Integrated,NaN,NaN,NaN,$591.99
Dell,Latitude 3420 Laptop,14 Inches,NaN,512 GB,Core i5,8 GB,Windows 10 Pro,NaN,Integrated,Intel Integrated Graphics,0.9 GHz,NaN,"$1,771.99"
Dell,Latitude 5430 Laptop,14 Inches,Black,256 GB,Core i5,NaN,Windows 11 Pro,NaN,Integrated,Intel Integrated Graphics,3.3 GHz,NaN,$938.99

In [63]:
laptop_corr=laptop.corr()
laptop_corr

        rating
rating     1.0

In [64]:
laptop_corr["rating"].sort_values(ascending=False)

rating    1.0
Name: rating, dtype: float64

there is no other feature to relate

### WEATHER

In [68]:
weather = pd.read_csv("GlobalWeatherRepository.csv.xls",index_col=[0])
weather

,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1693301400,2023-08-29 14:00,28.8,83.8,Sunny,7.2,...,7.9,11.1,1,1,05:24 AM,06:24 PM,05:39 PM,02:48 AM,Waxing Gibbous,93
Albania,Tirana,41.33,19.82,Europe/Tirane,1693301400,2023-08-29 11:30,27.0,80.6,Partly cloudy,3.8,...,28.2,29.6,2,3,06:04 AM,07:19 PM,06:50 PM,03:25 AM,Waxing Gibbous,93
Algeria,Algiers,36.76,3.05,Africa/Algiers,1693301400,2023-08-29 10:30,28.0,82.4,Partly cloudy,8.1,...,6.4,7.9,1,1,06:16 AM,07:21 PM,06:46 PM,03:50 AM,Waxing Gibbous,93
Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1693301400,2023-08-29 11:30,10.2,50.4,Sunny,6.0,...,0.5,0.8,1,1,07:16 AM,08:34 PM,08:08 PM,04:38 AM,Waxing Gibbous,93
Angola,Luanda,-8.84,13.23,Africa/Luanda,1693301400,2023-08-29 10:30,25.0,77.0,Partly cloudy,2.2,...,139.6,203.3,4,10,06:11 AM,06:06 PM,04:43 PM,04:41 AM,Waxing Gibbous,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,Caracas,10.50,-66.92,America/Caracas,1697403600,2023-10-15 17:00,34.0,93.2,Sunny,6.9,...,20.2,21.0,2,2,06:16 AM,06:10 PM,06:53 AM,06:53 PM,Waxing Crescent,0
Vietnam,Hanoi,21.03,105.85,Asia/Bangkok,1697403600,2023-10-16 04:00,23.0,73.4,Clear,3.8,...,56.3,68.6,3,7,05:52 AM,05:33 PM,06:07 AM,05:53 PM,Waxing Crescent,0
Yemen,Sanaa,15.35,44.21,Asia/Aden,1697403600,2023-10-16 00:00,15.0,59.0,Clear,3.6,...,31.8,94.4,2,3,05:55 AM,05:43 PM,06:17 AM,06:11 PM,Waxing Crescent,0
Zambia,Lusaka,-15.42,28.28,Africa/Lusaka,1697403600,2023-10-15 23:00,26.6,80.0,Clear,8.1,...,17.5,23.0,2,2,05:40 AM,06:06 PM,06:00 AM,06:47 PM,Waxing Crescent,0
Zimbabwe,Harare,-17.82,31.04,Africa/Harare,1697403600,2023-10-15 23:00,19.3,66.7,Clear,8.5,...,20.7,25.4,2,2,05:28 AM,05:56 PM,05:47 AM,06:38 PM,Waxing Crescent,0

In [69]:
weather_corr = weather.corr()
weather_corr

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
latitude,1.000000,-0.013652,-0.000265,-0.343188,-0.343211,-0.089537,-0.089568,0.104342,0.071149,0.071993,...,-0.084009,-0.105555,0.080944,0.127028,0.032758,-0.046834,-0.054657,-0.005352,-0.008995,0.000016
longitude,-0.013652,1.000000,0.000785,-0.152681,-0.152685,-0.125799,-0.125923,0.002040,-0.008029,-0.006817,...,-0.035264,0.113466,-0.167471,0.093191,0.075764,0.145561,0.127850,0.175107,0.179078,-0.000854
last_updated_epoch,-0.000265,0.000785,1.000000,-0.072088,-0.072083,0.022586,0.022797,0.020470,0.075125,0.076631,...,0.004334,0.024706,-0.002390,0.042123,0.014845,0.040730,0.056908,0.070022,0.069589,-0.285076
temperature_celsius,-0.343188,-0.152681,-0.072088,1.000000,0.999998,0.067190,0.066926,-0.043798,-0.504498,-0.505826,...,0.125998,0.045992,0.113384,-0.038105,0.042028,0.061826,0.117244,0.107174,0.109744,-0.001496
temperature_fahrenheit,-0.343211,-0.152685,-0.072083,0.999998,1.000000,0.067179,0.066914,-0.043808,-0.504510,-0.505838,...,0.125986,0.046000,0.113376,-0.038101,0.042020,0.061842,0.117267,0.107217,0.109792,-0.001484
wind_mph,-0.089537,-0.125799,0.022586,0.067190,0.067179,1.000000,0.999965,0.111613,-0.178988,-0.179342,...,0.557822,-0.101032,0.208514,-0.183194,-0.106370,-0.124194,-0.106509,-0.198997,-0.189034,-0.002942
wind_kph,-0.089568,-0.125923,0.022797,0.066926,0.066914,0.999965,1.000000,0.110591,-0.178972,-0.179335,...,0.557727,-0.101174,0.208757,-0.183401,-0.106457,-0.124381,-0.106752,-0.199256,-0.189275,-0.003215
wind_degree,0.104342,0.002040,0.020470,-0.043798,-0.043808,0.111613,0.110591,1.000000,-0.033534,-0.033660,...,0.041776,0.000429,0.056295,-0.013860,-0.025622,-0.006300,0.005018,-0.008910,-0.014754,0.015274
pressure_mb,0.071149,-0.008029,0.075125,-0.504498,-0.504510,-0.178988,-0.178972,-0.033534,1.000000,0.999496,...,-0.216659,-0.046359,-0.076925,0.039830,-0.031512,-0.058255,-0.084986,-0.084099,-0.097835,0.036143
pressure_in,0.071993,-0.006817,0.076631,-0.505826,-0.505838,-0.179342,-0.179335,-0.033660,0.999496,1.000000,...,-0.217165,-0.046329,-0.077250,0.040715,-0.030598,-0.057858,-0.084263,-0.083056,-0.096699,0.036865
precip_mm,-0.034173,-0.028194,-0.034370,0.053229,0.053204,0.032442,0.032373,0.026408,-0.075541,-0.075356,...,0.036132,-0.005635,-0.033076,-0.025116,0.012548,-0.029645,-0.040789,-0.044195,-0.038986,0.049170
precip_in,-0.033135,-0.028390,-0.033960,0.053039,0.053014,0.031381,0.031313,0.026813,-0.074512,-0.074307,...,0.033768,-0.005461,-0.032756,-0.024093,0.013249,-0.029186,-0.040297,-0.043458,-0.038479,0.048604
humidity,0.119778,0.135106,-0.033313,-0.208971,-0.208973,-0.082823,-0.082949,0.046372,0.016554,0.017237,...,-0.050005,0.065515,-0.312890,-0.064996,-0.109724,0.031789,-0.042075,-0.048794,-0.044268,0.025086
cloud,-0.142290,0.053223,-0.022239,0.078305,0.078279,0.158747,0.158884,0.028947,-0.165108,-0.165628,...,0.112272,-0.013997,-0.100927,-0.144439,-0.072965,-0.083601,-0.119518,-0.172001,-0.155472,0.023103
feels_like_celsius,-0.333080,-0.173510,-0.063974,0.971978,0.971971,0.065552,0.065311,-0.047073,-0.484716,-0.485850,...,0.101886,0.039667,0.093382,-0.049223,0.043142,0.044970,0.086554,0.080190,0.085837,0.004392
feels_like_fahrenheit,-0.333140,-0.173473,-0.064010,0.971986,0.971980,0.065491,0.065250,-0.047099,-0.484759,-0.485892,...,0.101854,0.039642,0.093339,-0.049272,0.043112,0.044913,0.086517,0.080176,0.085836,0.004424
visibility_km,-0.010526,0.001348,-0.008903,0.071546,0.071555,0.051884,0.051782,-0.009153,0.039663,0.037379,...,0.107400,-0.159916,0.066098,-0.111254,-0.085987,-0.196141,-0.196722,-0.194722,-0.185267,0.001100
visibility_miles,-0.009808,-0.003877,-0.010427,0.054433,0.054443,0.061144,0.061050,-0.010591,0.050822,0.048700,...,0.115389,-0.170038,0.073535,-0.112678,-0.089614,-0.208093,-0.207651,-0.208096,-0.198498,0.003449
uv_index,-0.222229,-0.182578,-0.042978,0.398819,0.398793,0.163542,0.163881,-0.054370,-0.186315,-0.187560,...,0.033206,-0.037091,0.127611,-0.075031,0.055695,-0.065827,-0.092903,-0.117452,-0.111955,-0.031148
gust_mph,-0.084055,-0.035311,0.004380,0.126054,0.126042,0.557835,0.557742,0.041710,-0.216726,-0.217232,...,0.999987,-0.150940,0.239271,-0.236867,-0.165885,-0.149959,-0.097355,-0.206583,-0.193061,0.018499
gust_kph,-0.084009,-0.035264,0.004334,0.125998,0.125986,0.557822,0.557727,0.041776,-0.216659,-0.217165,...,1.000000,-0.150901,0.239258,-0.236743,-0.165874,-0.149876,-0.097272,-0.206504,-0.192993,0.018636
air_quality_Carbon_Monoxide,-0.105555,0.113466,0.024706,0.045992,0.046000,-0.101032,-0.101174,0.000429,-0.046359,-0.046329,...,-0.150901,1.000000,-0.194165,0.510306,0.387185,0.898766,0.753502,0.558782,0.481637,-0.009442
air_quality_Ozone,0.080944,-0.167471,-0.002390,0.113384,0.113376,0.208514,0.208757,0.056295,-0.076925,-0.077250,...,0.239258,-0.194165,1.000000,-0.288434,-0.039942,-0.125517,-0.065344,-0.075899,-0.070505,-0.032924
air_quality_Nitrogen_dioxide,0.127028,0.093191,0.042123,-0.038105,-0.038101,-0.183194,-0.183401,-0.013860,0.039830,0.040715,...,-0.236743,0.510306,-0.288434,1.000000,0.702992,0.507385,0.422014,0.514550,0.480057,-0.007295
air_quality_Sulphur_dioxide,0.032758,0.075764,0.014845,0.042028,0.042020,-0.106370,-0.106457,-0.025622,-0.031512,-0.030598,...,-0.165874,0.387185,-0.039942,0.702992,1.000000,0.403013,0.344048,0.441060,0.425334,-0.009402
air_quality_PM2.5,-0.046834,0.145561,0.040730,0.061826,0.061842,-0.124194,-0.124381,-0.006300,-0.058255,-0.057858,...,-0.149876,0.898766,-0.125517,0.507385,0.403013,1.000000,0.909002,0.731761,0.648959,-0.012835
air_quality_PM10,-0.054657,0.127850,0.056908,0.117244,0.117267,-0.106509,-0.106752,0.005018,-0.084986,-0.084263,...,-0.097272,0.753502,-0.065344,0.422014,0.344048,0.909002,1.000000,0.726187,0.657109,-0.012189
air_quality_us-epa-index,-0.005352,0.175107,0.070022,0.107174,0.107217,-0.198997,-0.199256,-0.008910,-0.084099,-0.083056,...,-0.206504,0.558782,-0.075899,0.514550,0.441060,0.731761,0.726187,1.000000,0.942991,-0.025699
air_quality_gb-defra-index,-0.008995,0.179078,0.069589,0.109744,0.109792,-0.189034,-0.189275,-0.014754,-0.097835,-0.096699,...,-0.192993,0.481637,-0.070505,0.480057,0.425334,0.648959,0.657109,0.942991,1.000000,-0.023866
moon_illumination,0.000016,-0.000854,-0.285076,-0.001496,-0.001484,-0.002942,-0.003215,0.015274,0.036143,0.036865,...,0.018636,-0.009442,-0.032924,-0.007295,-0.009402,-0.012835,-0.012189,-0.025699,-0.023866,1.000000

In [72]:
weather_corr.columns

Index(['latitude', 'longitude', 'last_updated_epoch', 'temperature_celsius',
       'temperature_fahrenheit', 'wind_mph', 'wind_kph', 'wind_degree',
       'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity',
       'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km',
       'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph',
       'air_quality_Carbon_Monoxide', 'air_quality_Ozone',
       'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide',
       'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index',
       'air_quality_gb-defra-index', 'moon_illumination'],
      dtype='object')

In [71]:
weather_corr["latitude"].sort_values(ascending=False)

latitude                        1.000000
air_quality_Nitrogen_dioxide    0.127028
humidity                        0.119778
wind_degree                     0.104342
air_quality_Ozone               0.080944
pressure_in                     0.071993
pressure_mb                     0.071149
air_quality_Sulphur_dioxide     0.032758
moon_illumination               0.000016
last_updated_epoch             -0.000265
air_quality_us-epa-index       -0.005352
air_quality_gb-defra-index     -0.008995
visibility_miles               -0.009808
visibility_km                  -0.010526
longitude                      -0.013652
precip_in                      -0.033135
precip_mm                      -0.034173
air_quality_PM2.5              -0.046834
air_quality_PM10               -0.054657
gust_kph                       -0.084009
gust_mph                       -0.084055
wind_mph                       -0.089537
wind_kph                       -0.089568
air_quality_Carbon_Monoxide    -0.105555
cloud                          -0.142290
uv_index                       -0.222229
feels_like_celsius             -0.333080
feels_like_fahrenheit          -0.333140
temperature_celsius            -0.343188
temperature_fahrenheit         -0.343211
Name: latitude, dtype: float64

   **from weather dataset**
   
      * lattitude shows:
           * air_quality_Nitrogen_dioxide have comparitively more +ve correlation
           * temperature_fahrenheit have comparitively more -ve correlation

In [77]:
weather_corr["longitude"].sort_values(ascending=False)

longitude                       1.000000
air_quality_gb-defra-index      0.179078
air_quality_us-epa-index        0.175107
air_quality_PM2.5               0.145561
humidity                        0.135106
air_quality_PM10                0.127850
air_quality_Carbon_Monoxide     0.113466
air_quality_Nitrogen_dioxide    0.093191
air_quality_Sulphur_dioxide     0.075764
cloud                           0.053223
wind_degree                     0.002040
visibility_km                   0.001348
last_updated_epoch              0.000785
moon_illumination              -0.000854
visibility_miles               -0.003877
pressure_in                    -0.006817
pressure_mb                    -0.008029
latitude                       -0.013652
precip_mm                      -0.028194
precip_in                      -0.028390
gust_kph                       -0.035264
gust_mph                       -0.035311
wind_mph                       -0.125799
wind_kph                       -0.125923
temperature_celsius            -0.152681
temperature_fahrenheit         -0.152685
air_quality_Ozone              -0.167471
feels_like_fahrenheit          -0.173473
feels_like_celsius             -0.173510
uv_index                       -0.182578
Name: longitude, dtype: float64

**from weather dataset**

      * longitude shows:
       * air_quality_gb-defra-index have comparitively more +ve correlation
       * uv_index  have comparitively more -ve correlation

In [78]:
weather_corr["latitude"].sort_values(ascending=False)

latitude                        1.000000
air_quality_Nitrogen_dioxide    0.127028
humidity                        0.119778
wind_degree                     0.104342
air_quality_Ozone               0.080944
pressure_in                     0.071993
pressure_mb                     0.071149
air_quality_Sulphur_dioxide     0.032758
moon_illumination               0.000016
last_updated_epoch             -0.000265
air_quality_us-epa-index       -0.005352
air_quality_gb-defra-index     -0.008995
visibility_miles               -0.009808
visibility_km                  -0.010526
longitude                      -0.013652
precip_in                      -0.033135
precip_mm                      -0.034173
air_quality_PM2.5              -0.046834
air_quality_PM10               -0.054657
gust_kph                       -0.084009
gust_mph                       -0.084055
wind_mph                       -0.089537
wind_kph                       -0.089568
air_quality_Carbon_Monoxide    -0.105555
cloud                          -0.142290
uv_index                       -0.222229
feels_like_celsius             -0.333080
feels_like_fahrenheit          -0.333140
temperature_celsius            -0.343188
temperature_fahrenheit         -0.343211
Name: latitude, dtype: float64

**from weather dataset**

    * lattitude shows:
       * air_quality_Nitrogen_dioxide have comparitively more +ve correlation
       * temperature_fahrenheit have comparitively more -ve correlation

In [79]:
weather_corr["last_updated_epoch"].sort_values(ascending=False)

last_updated_epoch              1.000000
pressure_in                     0.076631
pressure_mb                     0.075125
air_quality_us-epa-index        0.070022
air_quality_gb-defra-index      0.069589
air_quality_PM10                0.056908
air_quality_Nitrogen_dioxide    0.042123
air_quality_PM2.5               0.040730
air_quality_Carbon_Monoxide     0.024706
wind_kph                        0.022797
wind_mph                        0.022586
wind_degree                     0.020470
air_quality_Sulphur_dioxide     0.014845
gust_mph                        0.004380
gust_kph                        0.004334
longitude                       0.000785
latitude                       -0.000265
air_quality_Ozone              -0.002390
visibility_km                  -0.008903
visibility_miles               -0.010427
cloud                          -0.022239
humidity                       -0.033313
precip_in                      -0.033960
precip_mm                      -0.034370
uv_index                       -0.042978
feels_like_celsius             -0.063974
feels_like_fahrenheit          -0.064010
temperature_fahrenheit         -0.072083
temperature_celsius            -0.072088
moon_illumination              -0.285076
Name: last_updated_epoch, dtype: float64

**from weather dataset**

     * last_updated_epoch shows:
       * pressure_in have comparitively more +ve correlation
       * moon_illumination  have comparitively more -ve correlation

In [80]:
weather_corr["temperature_celsius"].sort_values(ascending=False)

temperature_celsius             1.000000
temperature_fahrenheit          0.999998
feels_like_fahrenheit           0.971986
feels_like_celsius              0.971978
uv_index                        0.398819
gust_mph                        0.126054
gust_kph                        0.125998
air_quality_PM10                0.117244
air_quality_Ozone               0.113384
air_quality_gb-defra-index      0.109744
air_quality_us-epa-index        0.107174
cloud                           0.078305
visibility_km                   0.071546
wind_mph                        0.067190
wind_kph                        0.066926
air_quality_PM2.5               0.061826
visibility_miles                0.054433
precip_mm                       0.053229
precip_in                       0.053039
air_quality_Carbon_Monoxide     0.045992
air_quality_Sulphur_dioxide     0.042028
moon_illumination              -0.001496
air_quality_Nitrogen_dioxide   -0.038105
wind_degree                    -0.043798
last_updated_epoch             -0.072088
longitude                      -0.152681
humidity                       -0.208971
latitude                       -0.343188
pressure_mb                    -0.504498
pressure_in                    -0.505826
Name: temperature_celsius, dtype: float64

**from weather dataset**

     * temperature_celsius shows:
        *temperature_fahrenheit,feels_like_fahrenheit,feels_like_celsius have comparitively more +ve correlation
        * pressure_in have comparitively more -ve correlation

In [81]:
weather_corr["temperature_fahrenheit"].sort_values(ascending=False)

temperature_fahrenheit          1.000000
temperature_celsius             0.999998
feels_like_fahrenheit           0.971980
feels_like_celsius              0.971971
uv_index                        0.398793
gust_mph                        0.126042
gust_kph                        0.125986
air_quality_PM10                0.117267
air_quality_Ozone               0.113376
air_quality_gb-defra-index      0.109792
air_quality_us-epa-index        0.107217
cloud                           0.078279
visibility_km                   0.071555
wind_mph                        0.067179
wind_kph                        0.066914
air_quality_PM2.5               0.061842
visibility_miles                0.054443
precip_mm                       0.053204
precip_in                       0.053014
air_quality_Carbon_Monoxide     0.046000
air_quality_Sulphur_dioxide     0.042020
moon_illumination              -0.001484
air_quality_Nitrogen_dioxide   -0.038101
wind_degree                    -0.043808
last_updated_epoch             -0.072083
longitude                      -0.152685
humidity                       -0.208973
latitude                       -0.343211
pressure_mb                    -0.504510
pressure_in                    -0.505838
Name: temperature_fahrenheit, dtype: float64

**from weather dataset**

      temperature_fahrenheit shows:
        *temperature_celsius,feels_like_fahrenheit,feels_like_celsius have comparitively more +ve correlation
        * pressure_in have comparitively more -ve correlation

In [82]:
weather_corr["wind_mph"].sort_values(ascending=False)

wind_mph                        1.000000
wind_kph                        0.999965
gust_mph                        0.557835
gust_kph                        0.557822
air_quality_Ozone               0.208514
uv_index                        0.163542
cloud                           0.158747
wind_degree                     0.111613
temperature_celsius             0.067190
temperature_fahrenheit          0.067179
feels_like_celsius              0.065552
feels_like_fahrenheit           0.065491
visibility_miles                0.061144
visibility_km                   0.051884
precip_mm                       0.032442
precip_in                       0.031381
last_updated_epoch              0.022586
moon_illumination              -0.002942
humidity                       -0.082823
latitude                       -0.089537
air_quality_Carbon_Monoxide    -0.101032
air_quality_Sulphur_dioxide    -0.106370
air_quality_PM10               -0.106509
air_quality_PM2.5              -0.124194
longitude                      -0.125799
pressure_mb                    -0.178988
pressure_in                    -0.179342
air_quality_Nitrogen_dioxide   -0.183194
air_quality_gb-defra-index     -0.189034
air_quality_us-epa-index       -0.198997
Name: wind_mph, dtype: float64

**from weather dataset**

     wind_mph shows:
        *wind_kph have comparitively more +ve correlation
        * air_quality_us-epa-index have comparitively more -ve correlation

In [83]:
weather_corr["wind_kph"].sort_values(ascending=False)

wind_kph                        1.000000
wind_mph                        0.999965
gust_mph                        0.557742
gust_kph                        0.557727
air_quality_Ozone               0.208757
uv_index                        0.163881
cloud                           0.158884
wind_degree                     0.110591
temperature_celsius             0.066926
temperature_fahrenheit          0.066914
feels_like_celsius              0.065311
feels_like_fahrenheit           0.065250
visibility_miles                0.061050
visibility_km                   0.051782
precip_mm                       0.032373
precip_in                       0.031313
last_updated_epoch              0.022797
moon_illumination              -0.003215
humidity                       -0.082949
latitude                       -0.089568
air_quality_Carbon_Monoxide    -0.101174
air_quality_Sulphur_dioxide    -0.106457
air_quality_PM10               -0.106752
air_quality_PM2.5              -0.124381
longitude                      -0.125923
pressure_mb                    -0.178972
pressure_in                    -0.179335
air_quality_Nitrogen_dioxide   -0.183401
air_quality_gb-defra-index     -0.189275
air_quality_us-epa-index       -0.199256
Name: wind_kph, dtype: float64

**from weather dataset**

     "wind_kph shows:
        *wind_mph have comparitively more +ve correlation
        * air_quality_us-epa-index more -ve correlation

In [84]:
weather_corr["wind_degree"].sort_values(ascending=False)

wind_degree                     1.000000
wind_mph                        0.111613
wind_kph                        0.110591
latitude                        0.104342
air_quality_Ozone               0.056295
humidity                        0.046372
gust_kph                        0.041776
gust_mph                        0.041710
cloud                           0.028947
precip_in                       0.026813
precip_mm                       0.026408
last_updated_epoch              0.020470
moon_illumination               0.015274
air_quality_PM10                0.005018
longitude                       0.002040
air_quality_Carbon_Monoxide     0.000429
air_quality_PM2.5              -0.006300
air_quality_us-epa-index       -0.008910
visibility_km                  -0.009153
visibility_miles               -0.010591
air_quality_Nitrogen_dioxide   -0.013860
air_quality_gb-defra-index     -0.014754
air_quality_Sulphur_dioxide    -0.025622
pressure_mb                    -0.033534
pressure_in                    -0.033660
temperature_celsius            -0.043798
temperature_fahrenheit         -0.043808
feels_like_celsius             -0.047073
feels_like_fahrenheit          -0.047099
uv_index                       -0.054370
Name: wind_degree, dtype: float64

**from weather dataset**

     wind_degree shows:
        * wind_mph have comparitively more  +ve correlation(strength is less)
        * uv_index  have comparitively more -ve correlation

In [75]:
weather_corr["pressure_mb"].sort_values(ascending=False)

pressure_mb                     1.000000
pressure_in                     0.999496
last_updated_epoch              0.075125
latitude                        0.071149
visibility_miles                0.050822
air_quality_Nitrogen_dioxide    0.039830
visibility_km                   0.039663
moon_illumination               0.036143
humidity                        0.016554
longitude                      -0.008029
air_quality_Sulphur_dioxide    -0.031512
wind_degree                    -0.033534
air_quality_Carbon_Monoxide    -0.046359
air_quality_PM2.5              -0.058255
precip_in                      -0.074512
precip_mm                      -0.075541
air_quality_Ozone              -0.076925
air_quality_us-epa-index       -0.084099
air_quality_PM10               -0.084986
air_quality_gb-defra-index     -0.097835
cloud                          -0.165108
wind_kph                       -0.178972
wind_mph                       -0.178988
uv_index                       -0.186315
gust_kph                       -0.216659
gust_mph                       -0.216726
feels_like_celsius             -0.484716
feels_like_fahrenheit          -0.484759
temperature_celsius            -0.504498
temperature_fahrenheit         -0.504510
Name: pressure_mb, dtype: float64

**from weather dataset**

     pressure_mb shows:
        * pressure_in have comparitively more +ve correlation
        * temperature_fahrenheit have comparitively more -ve correlation

In [88]:
weather_corr["pressure_in"].sort_values(ascending=False)

pressure_in                     1.000000
pressure_mb                     0.999496
last_updated_epoch              0.076631
latitude                        0.071993
visibility_miles                0.048700
air_quality_Nitrogen_dioxide    0.040715
visibility_km                   0.037379
moon_illumination               0.036865
humidity                        0.017237
longitude                      -0.006817
air_quality_Sulphur_dioxide    -0.030598
wind_degree                    -0.033660
air_quality_Carbon_Monoxide    -0.046329
air_quality_PM2.5              -0.057858
precip_in                      -0.074307
precip_mm                      -0.075356
air_quality_Ozone              -0.077250
air_quality_us-epa-index       -0.083056
air_quality_PM10               -0.084263
air_quality_gb-defra-index     -0.096699
cloud                          -0.165628
wind_kph                       -0.179335
wind_mph                       -0.179342
uv_index                       -0.187560
gust_kph                       -0.217165
gust_mph                       -0.217232
feels_like_celsius             -0.485850
feels_like_fahrenheit          -0.485892
temperature_celsius            -0.505826
temperature_fahrenheit         -0.505838
Name: pressure_in, dtype: float64

**from weather dataset**

     pressure_in shows:
        * pressure_mb have comparitively more +ve correlation
        * temperature_fahrenheit have comparitively more -ve correlation

In [89]:
weather_corr["precip_mm"].sort_values(ascending=False)

precip_mm                       1.000000
precip_in                       0.999240
cloud                           0.187404
humidity                        0.119271
feels_like_celsius              0.082015
feels_like_fahrenheit           0.082000
temperature_celsius             0.053229
temperature_fahrenheit          0.053204
moon_illumination               0.049170
uv_index                        0.038769
gust_mph                        0.036171
gust_kph                        0.036132
wind_mph                        0.032442
wind_kph                        0.032373
wind_degree                     0.026408
air_quality_Sulphur_dioxide     0.012548
air_quality_Carbon_Monoxide    -0.005635
visibility_km                  -0.018121
air_quality_Nitrogen_dioxide   -0.025116
visibility_miles               -0.025341
longitude                      -0.028194
air_quality_PM2.5              -0.029645
air_quality_Ozone              -0.033076
latitude                       -0.034173
last_updated_epoch             -0.034370
air_quality_gb-defra-index     -0.038986
air_quality_PM10               -0.040789
air_quality_us-epa-index       -0.044195
pressure_in                    -0.075356
pressure_mb                    -0.075541
Name: precip_mm, dtype: float64

**from weather dataset**

    precip_mm shows:
        * precip_in have comparitively more +ve correlation
        * pressure_mb have comparitively more -ve correlation

In [91]:
weather_corr["humidity"].sort_values(ascending=False)

humidity                        1.000000
cloud                           0.365994
longitude                       0.135106
latitude                        0.119778
precip_mm                       0.119271
precip_in                       0.117617
air_quality_Carbon_Monoxide     0.065515
wind_degree                     0.046372
air_quality_PM2.5               0.031789
moon_illumination               0.025086
pressure_in                     0.017237
pressure_mb                     0.016554
last_updated_epoch             -0.033313
air_quality_PM10               -0.042075
air_quality_gb-defra-index     -0.044268
air_quality_us-epa-index       -0.048794
gust_mph                       -0.049949
gust_kph                       -0.050005
air_quality_Nitrogen_dioxide   -0.064996
wind_mph                       -0.082823
wind_kph                       -0.082949
air_quality_Sulphur_dioxide    -0.109724
uv_index                       -0.117702
feels_like_fahrenheit          -0.121092
feels_like_celsius             -0.121142
visibility_km                  -0.151302
visibility_miles               -0.163609
temperature_celsius            -0.208971
temperature_fahrenheit         -0.208973
air_quality_Ozone              -0.312890
Name: humidity, dtype: float64

**from weather dataset**

     humidity shows:
        *none of the points are showing correlation as the values are more close to 0

In [92]:
weather_corr["visibility_miles"].sort_values(ascending=False)

visibility_miles                1.000000
visibility_km                   0.991276
uv_index                        0.190137
gust_mph                        0.115495
gust_kph                        0.115389
air_quality_Ozone               0.073535
wind_mph                        0.061144
wind_kph                        0.061050
feels_like_fahrenheit           0.059195
feels_like_celsius              0.059193
temperature_fahrenheit          0.054443
temperature_celsius             0.054433
pressure_mb                     0.050822
pressure_in                     0.048700
cloud                           0.040740
moon_illumination               0.003449
longitude                      -0.003877
latitude                       -0.009808
last_updated_epoch             -0.010427
wind_degree                    -0.010591
precip_mm                      -0.025341
precip_in                      -0.025535
air_quality_Sulphur_dioxide    -0.089614
air_quality_Nitrogen_dioxide   -0.112678
humidity                       -0.163609
air_quality_Carbon_Monoxide    -0.170038
air_quality_gb-defra-index     -0.198498
air_quality_PM10               -0.207651
air_quality_PM2.5              -0.208093
air_quality_us-epa-index       -0.208096
Name: visibility_miles, dtype: float64

**from weather dataset**

     visibility_miles shows:
        * visibility_km  have comparitively more +ve correlation
        * air_quality_us-epa-index have comparitively more -ve correlation

In [93]:
weather_corr["uv_index"].sort_values(ascending=False)

uv_index                        1.000000
feels_like_celsius              0.426020
feels_like_fahrenheit           0.425984
temperature_celsius             0.398819
temperature_fahrenheit          0.398793
visibility_km                   0.199564
cloud                           0.199074
visibility_miles                0.190137
wind_kph                        0.163881
wind_mph                        0.163542
air_quality_Ozone               0.127611
air_quality_Sulphur_dioxide     0.055695
precip_mm                       0.038769
precip_in                       0.038667
gust_mph                        0.033290
gust_kph                        0.033206
moon_illumination              -0.031148
air_quality_Carbon_Monoxide    -0.037091
last_updated_epoch             -0.042978
wind_degree                    -0.054370
air_quality_PM2.5              -0.065827
air_quality_Nitrogen_dioxide   -0.075031
air_quality_PM10               -0.092903
air_quality_gb-defra-index     -0.111955
air_quality_us-epa-index       -0.117452
humidity                       -0.117702
longitude                      -0.182578
pressure_mb                    -0.186315
pressure_in                    -0.187560
latitude                       -0.222229
Name: uv_index, dtype: float64

**from weather dataset**

    uv_index shows:
        *

In [94]:
weather_corr["gust_mph"].sort_values(ascending=False)

gust_mph                        1.000000
gust_kph                        0.999987
wind_mph                        0.557835
wind_kph                        0.557742
air_quality_Ozone               0.239271
temperature_celsius             0.126054
temperature_fahrenheit          0.126042
visibility_miles                0.115495
cloud                           0.112338
visibility_km                   0.107519
feels_like_celsius              0.101972
feels_like_fahrenheit           0.101940
wind_degree                     0.041710
precip_mm                       0.036171
precip_in                       0.033808
uv_index                        0.033290
moon_illumination               0.018499
last_updated_epoch              0.004380
longitude                      -0.035311
humidity                       -0.049949
latitude                       -0.084055
air_quality_PM10               -0.097355
air_quality_PM2.5              -0.149959
air_quality_Carbon_Monoxide    -0.150940
air_quality_Sulphur_dioxide    -0.165885
air_quality_gb-defra-index     -0.193061
air_quality_us-epa-index       -0.206583
pressure_mb                    -0.216726
pressure_in                    -0.217232
air_quality_Nitrogen_dioxide   -0.236867
Name: gust_mph, dtype: float64

**from weather dataset**

    gust_mph shows:
        * gust_kph have comparitively more +ve correlation
        * air_quality_Nitrogen_dioxide have comparitively more -ve correlation

In [95]:
weather_corr["gust_kph"].sort_values(ascending=False)

gust_kph                        1.000000
gust_mph                        0.999987
wind_mph                        0.557822
wind_kph                        0.557727
air_quality_Ozone               0.239258
temperature_celsius             0.125998
temperature_fahrenheit          0.125986
visibility_miles                0.115389
cloud                           0.112272
visibility_km                   0.107400
feels_like_celsius              0.101886
feels_like_fahrenheit           0.101854
wind_degree                     0.041776
precip_mm                       0.036132
precip_in                       0.033768
uv_index                        0.033206
moon_illumination               0.018636
last_updated_epoch              0.004334
longitude                      -0.035264
humidity                       -0.050005
latitude                       -0.084009
air_quality_PM10               -0.097272
air_quality_PM2.5              -0.149876
air_quality_Carbon_Monoxide    -0.150901
air_quality_Sulphur_dioxide    -0.165874
air_quality_gb-defra-index     -0.192993
air_quality_us-epa-index       -0.206504
pressure_mb                    -0.216659
pressure_in                    -0.217165
air_quality_Nitrogen_dioxide   -0.236743
Name: gust_kph, dtype: float64

**from weather dataset**

    gust_kph shows:
        * gust_mph have comparitively more +ve correlation
        * gust_mph have comparitively more -ve correlation

In [96]:
weather_corr["cloud"].sort_values(ascending=False)

cloud                           1.000000
humidity                        0.365994
uv_index                        0.199074
precip_mm                       0.187404
precip_in                       0.183851
wind_kph                        0.158884
wind_mph                        0.158747
feels_like_fahrenheit           0.114280
feels_like_celsius              0.114242
gust_mph                        0.112338
gust_kph                        0.112272
temperature_celsius             0.078305
temperature_fahrenheit          0.078279
visibility_km                   0.059425
longitude                       0.053223
visibility_miles                0.040740
wind_degree                     0.028947
moon_illumination               0.023103
air_quality_Carbon_Monoxide    -0.013997
last_updated_epoch             -0.022239
air_quality_Sulphur_dioxide    -0.072965
air_quality_PM2.5              -0.083601
air_quality_Ozone              -0.100927
air_quality_PM10               -0.119518
latitude                       -0.142290
air_quality_Nitrogen_dioxide   -0.144439
air_quality_gb-defra-index     -0.155472
pressure_mb                    -0.165108
pressure_in                    -0.165628
air_quality_us-epa-index       -0.172001
Name: cloud, dtype: float64

**from weather dataset**

     cloud shows:
        *

In [97]:
weather_corr["feels_like_celsius"].sort_values(ascending=False)

feels_like_celsius              1.000000
feels_like_fahrenheit           0.999995
temperature_celsius             0.971978
temperature_fahrenheit          0.971971
uv_index                        0.426020
cloud                           0.114242
gust_mph                        0.101972
gust_kph                        0.101886
air_quality_Ozone               0.093382
air_quality_PM10                0.086554
air_quality_gb-defra-index      0.085837
precip_mm                       0.082015
precip_in                       0.081609
air_quality_us-epa-index        0.080190
visibility_km                   0.076163
wind_mph                        0.065552
wind_kph                        0.065311
visibility_miles                0.059193
air_quality_PM2.5               0.044970
air_quality_Sulphur_dioxide     0.043142
air_quality_Carbon_Monoxide     0.039667
moon_illumination               0.004392
wind_degree                    -0.047073
air_quality_Nitrogen_dioxide   -0.049223
last_updated_epoch             -0.063974
humidity                       -0.121142
longitude                      -0.173510
latitude                       -0.333080
pressure_mb                    -0.484716
pressure_in                    -0.485850
Name: feels_like_celsius, dtype: float64

**from weather dataset**

     feels_like_celsius shows:
        * feels_like_fahrenheit,feels_like_celsius,temperature_fahrenheit have comparitively more +ve correlation
        * pressure_in have comparitively more -ve correlation

In [98]:
weather_corr["feels_like_fahrenheit"].sort_values(ascending=False)

feels_like_fahrenheit           1.000000
feels_like_celsius              0.999995
temperature_celsius             0.971986
temperature_fahrenheit          0.971980
uv_index                        0.425984
cloud                           0.114280
gust_mph                        0.101940
gust_kph                        0.101854
air_quality_Ozone               0.093339
air_quality_PM10                0.086517
air_quality_gb-defra-index      0.085836
precip_mm                       0.082000
precip_in                       0.081594
air_quality_us-epa-index        0.080176
visibility_km                   0.076163
wind_mph                        0.065491
wind_kph                        0.065250
visibility_miles                0.059195
air_quality_PM2.5               0.044913
air_quality_Sulphur_dioxide     0.043112
air_quality_Carbon_Monoxide     0.039642
moon_illumination               0.004424
wind_degree                    -0.047099
air_quality_Nitrogen_dioxide   -0.049272
last_updated_epoch             -0.064010
humidity                       -0.121092
longitude                      -0.173473
latitude                       -0.333140
pressure_mb                    -0.484759
pressure_in                    -0.485892
Name: feels_like_fahrenheit, dtype: float64

**from weather dataset**

     feels_like_fahrenheit shows:
        * feels_like_celsius,temperature_celsius,temperature_fahrenheit have comparitively more +ve correlation
        * pressure_in have comparitively more -ve correlation

In [99]:
weather_corr["visibility_km"].sort_values(ascending=False)

visibility_km                   1.000000
visibility_miles                0.991276
uv_index                        0.199564
gust_mph                        0.107519
gust_kph                        0.107400
feels_like_celsius              0.076163
feels_like_fahrenheit           0.076163
temperature_fahrenheit          0.071555
temperature_celsius             0.071546
air_quality_Ozone               0.066098
cloud                           0.059425
wind_mph                        0.051884
wind_kph                        0.051782
pressure_mb                     0.039663
pressure_in                     0.037379
longitude                       0.001348
moon_illumination               0.001100
last_updated_epoch             -0.008903
wind_degree                    -0.009153
latitude                       -0.010526
precip_mm                      -0.018121
precip_in                      -0.018244
air_quality_Sulphur_dioxide    -0.085987
air_quality_Nitrogen_dioxide   -0.111254
humidity                       -0.151302
air_quality_Carbon_Monoxide    -0.159916
air_quality_gb-defra-index     -0.185267
air_quality_us-epa-index       -0.194722
air_quality_PM2.5              -0.196141
air_quality_PM10               -0.196722
Name: visibility_km, dtype: float64

**from weather dataset**

     visibility_km shows:
        * visibility_miles have comparitively more +ve correlation
        * air_quality_PM10 have comparitively more -ve correlation

In [100]:
weather_corr["air_quality_Carbon_Monoxide"].sort_values(ascending=False)

air_quality_Carbon_Monoxide     1.000000
air_quality_PM2.5               0.898766
air_quality_PM10                0.753502
air_quality_us-epa-index        0.558782
air_quality_Nitrogen_dioxide    0.510306
air_quality_gb-defra-index      0.481637
air_quality_Sulphur_dioxide     0.387185
longitude                       0.113466
humidity                        0.065515
temperature_fahrenheit          0.046000
temperature_celsius             0.045992
feels_like_celsius              0.039667
feels_like_fahrenheit           0.039642
last_updated_epoch              0.024706
wind_degree                     0.000429
precip_in                      -0.005461
precip_mm                      -0.005635
moon_illumination              -0.009442
cloud                          -0.013997
uv_index                       -0.037091
pressure_in                    -0.046329
pressure_mb                    -0.046359
wind_mph                       -0.101032
wind_kph                       -0.101174
latitude                       -0.105555
gust_kph                       -0.150901
gust_mph                       -0.150940
visibility_km                  -0.159916
visibility_miles               -0.170038
air_quality_Ozone              -0.194165
Name: air_quality_Carbon_Monoxide, dtype: float64

**from weather dataset**

    air_quality_Carbon_Monoxide shows:
        * air_quality_PM2.5  have comparitively more +ve correlation
        * air_quality_Ozone have comparitively more -ve correlation

In [101]:
weather_corr["air_quality_Ozone"].sort_values(ascending=False)

air_quality_Ozone               1.000000
gust_mph                        0.239271
gust_kph                        0.239258
wind_kph                        0.208757
wind_mph                        0.208514
uv_index                        0.127611
temperature_celsius             0.113384
temperature_fahrenheit          0.113376
feels_like_celsius              0.093382
feels_like_fahrenheit           0.093339
latitude                        0.080944
visibility_miles                0.073535
visibility_km                   0.066098
wind_degree                     0.056295
last_updated_epoch             -0.002390
precip_in                      -0.032756
moon_illumination              -0.032924
precip_mm                      -0.033076
air_quality_Sulphur_dioxide    -0.039942
air_quality_PM10               -0.065344
air_quality_gb-defra-index     -0.070505
air_quality_us-epa-index       -0.075899
pressure_mb                    -0.076925
pressure_in                    -0.077250
cloud                          -0.100927
air_quality_PM2.5              -0.125517
longitude                      -0.167471
air_quality_Carbon_Monoxide    -0.194165
air_quality_Nitrogen_dioxide   -0.288434
humidity                       -0.312890
Name: air_quality_Ozone, dtype: float64

**from weather dataset**

     air_quality_Ozone shows:
        *

In [102]:
weather_corr["air_quality_Nitrogen_dioxide"].sort_values(ascending=False)

air_quality_Nitrogen_dioxide    1.000000
air_quality_Sulphur_dioxide     0.702992
air_quality_us-epa-index        0.514550
air_quality_Carbon_Monoxide     0.510306
air_quality_PM2.5               0.507385
air_quality_gb-defra-index      0.480057
air_quality_PM10                0.422014
latitude                        0.127028
longitude                       0.093191
last_updated_epoch              0.042123
pressure_in                     0.040715
pressure_mb                     0.039830
moon_illumination              -0.007295
wind_degree                    -0.013860
precip_in                      -0.024093
precip_mm                      -0.025116
temperature_fahrenheit         -0.038101
temperature_celsius            -0.038105
feels_like_celsius             -0.049223
feels_like_fahrenheit          -0.049272
humidity                       -0.064996
uv_index                       -0.075031
visibility_km                  -0.111254
visibility_miles               -0.112678
cloud                          -0.144439
wind_mph                       -0.183194
wind_kph                       -0.183401
gust_kph                       -0.236743
gust_mph                       -0.236867
air_quality_Ozone              -0.288434
Name: air_quality_Nitrogen_dioxide, dtype: float64

**from weather dataset**

     air_quality_Nitrogen_dioxide shows:
        * air_quality_Sulphur_dioxide have comparitively more +ve correlation
        * air_quality_Ozone have comparitively more -ve correlation

In [103]:
weather_corr["air_quality_Sulphur_dioxide"].sort_values(ascending=False)

air_quality_Sulphur_dioxide     1.000000
air_quality_Nitrogen_dioxide    0.702992
air_quality_us-epa-index        0.441060
air_quality_gb-defra-index      0.425334
air_quality_PM2.5               0.403013
air_quality_Carbon_Monoxide     0.387185
air_quality_PM10                0.344048
longitude                       0.075764
uv_index                        0.055695
feels_like_celsius              0.043142
feels_like_fahrenheit           0.043112
temperature_celsius             0.042028
temperature_fahrenheit          0.042020
latitude                        0.032758
last_updated_epoch              0.014845
precip_in                       0.013249
precip_mm                       0.012548
moon_illumination              -0.009402
wind_degree                    -0.025622
pressure_in                    -0.030598
pressure_mb                    -0.031512
air_quality_Ozone              -0.039942
cloud                          -0.072965
visibility_km                  -0.085987
visibility_miles               -0.089614
wind_mph                       -0.106370
wind_kph                       -0.106457
humidity                       -0.109724
gust_kph                       -0.165874
gust_mph                       -0.165885
Name: air_quality_Sulphur_dioxide, dtype: float64

**from weather dataset**

    air_quality_Sulphur_dioxide shows:
        * air_quality_Nitrogen_dioxide have comparitively more +ve correlation
        * gust_mph  have comparitively more -ve correlation

In [104]:
weather_corr["air_quality_PM2.5"].sort_values(ascending=False)

air_quality_PM2.5               1.000000
air_quality_PM10                0.909002
air_quality_Carbon_Monoxide     0.898766
air_quality_us-epa-index        0.731761
air_quality_gb-defra-index      0.648959
air_quality_Nitrogen_dioxide    0.507385
air_quality_Sulphur_dioxide     0.403013
longitude                       0.145561
temperature_fahrenheit          0.061842
temperature_celsius             0.061826
feels_like_celsius              0.044970
feels_like_fahrenheit           0.044913
last_updated_epoch              0.040730
humidity                        0.031789
wind_degree                    -0.006300
moon_illumination              -0.012835
precip_in                      -0.029186
precip_mm                      -0.029645
latitude                       -0.046834
pressure_in                    -0.057858
pressure_mb                    -0.058255
uv_index                       -0.065827
cloud                          -0.083601
wind_mph                       -0.124194
wind_kph                       -0.124381
air_quality_Ozone              -0.125517
gust_kph                       -0.149876
gust_mph                       -0.149959
visibility_km                  -0.196141
visibility_miles               -0.208093
Name: air_quality_PM2.5, dtype: float64

**from weather dataset**

    air_quality_PM2.5 shows:
        * air_quality_PM10 ,air_quality_Carbon_Monoxide, have comparitively more +ve correlation
        * visibility_miles have comparitively more -ve correlation

In [90]:
weather_corr["air_quality_PM10"].sort_values(ascending=False)

air_quality_PM10                1.000000
air_quality_PM2.5               0.909002
air_quality_Carbon_Monoxide     0.753502
air_quality_us-epa-index        0.726187
air_quality_gb-defra-index      0.657109
air_quality_Nitrogen_dioxide    0.422014
air_quality_Sulphur_dioxide     0.344048
longitude                       0.127850
temperature_fahrenheit          0.117267
temperature_celsius             0.117244
feels_like_celsius              0.086554
feels_like_fahrenheit           0.086517
last_updated_epoch              0.056908
wind_degree                     0.005018
moon_illumination              -0.012189
precip_in                      -0.040297
precip_mm                      -0.040789
humidity                       -0.042075
latitude                       -0.054657
air_quality_Ozone              -0.065344
pressure_in                    -0.084263
pressure_mb                    -0.084986
uv_index                       -0.092903
gust_kph                       -0.097272
gust_mph                       -0.097355
wind_mph                       -0.106509
wind_kph                       -0.106752
cloud                          -0.119518
visibility_km                  -0.196722
visibility_miles               -0.207651
Name: air_quality_PM10, dtype: float64

**from weather dataset**

     air_quality_PM10 shows:
        * air_quality_PM2.5  have comparitively more +ve correlation
        * visibility_miles have comparitively more -ve correlation

In [87]:
weather_corr["air_quality_us-epa-index"].sort_values(ascending=False)

air_quality_us-epa-index        1.000000
air_quality_gb-defra-index      0.942991
air_quality_PM2.5               0.731761
air_quality_PM10                0.726187
air_quality_Carbon_Monoxide     0.558782
air_quality_Nitrogen_dioxide    0.514550
air_quality_Sulphur_dioxide     0.441060
longitude                       0.175107
temperature_fahrenheit          0.107217
temperature_celsius             0.107174
feels_like_celsius              0.080190
feels_like_fahrenheit           0.080176
last_updated_epoch              0.070022
latitude                       -0.005352
wind_degree                    -0.008910
moon_illumination              -0.025699
precip_in                      -0.043458
precip_mm                      -0.044195
humidity                       -0.048794
air_quality_Ozone              -0.075899
pressure_in                    -0.083056
pressure_mb                    -0.084099
uv_index                       -0.117452
cloud                          -0.172001
visibility_km                  -0.194722
wind_mph                       -0.198997
wind_kph                       -0.199256
gust_kph                       -0.206504
gust_mph                       -0.206583
visibility_miles               -0.208096
Name: air_quality_us-epa-index, dtype: float64

**from weather dataset**

     air_quality_us-epa-index shows:
        *air_quality_gb-defra-index  have comparitively more +ve correlation
        * visibility_miles have comparitively more -ve correlation

In [86]:
weather_corr["air_quality_gb-defra-index"].sort_values(ascending=False)

air_quality_gb-defra-index      1.000000
air_quality_us-epa-index        0.942991
air_quality_PM10                0.657109
air_quality_PM2.5               0.648959
air_quality_Carbon_Monoxide     0.481637
air_quality_Nitrogen_dioxide    0.480057
air_quality_Sulphur_dioxide     0.425334
longitude                       0.179078
temperature_fahrenheit          0.109792
temperature_celsius             0.109744
feels_like_celsius              0.085837
feels_like_fahrenheit           0.085836
last_updated_epoch              0.069589
latitude                       -0.008995
wind_degree                    -0.014754
moon_illumination              -0.023866
precip_in                      -0.038479
precip_mm                      -0.038986
humidity                       -0.044268
air_quality_Ozone              -0.070505
pressure_in                    -0.096699
pressure_mb                    -0.097835
uv_index                       -0.111955
cloud                          -0.155472
visibility_km                  -0.185267
wind_mph                       -0.189034
wind_kph                       -0.189275
gust_kph                       -0.192993
gust_mph                       -0.193061
visibility_miles               -0.198498
Name: air_quality_gb-defra-index, dtype: float64

**from weather dataset**

     air_quality_gb-defra-index shows:
        * air_quality_us-epa-index have comparitively more +ve correlation
        * visibility_miles have comparitively more -ve correlation

In [85]:
weather_corr["moon_illumination"].sort_values(ascending=False)

moon_illumination               1.000000
precip_mm                       0.049170
precip_in                       0.048604
pressure_in                     0.036865
pressure_mb                     0.036143
humidity                        0.025086
cloud                           0.023103
gust_kph                        0.018636
gust_mph                        0.018499
wind_degree                     0.015274
feels_like_fahrenheit           0.004424
feels_like_celsius              0.004392
visibility_miles                0.003449
visibility_km                   0.001100
latitude                        0.000016
longitude                      -0.000854
temperature_fahrenheit         -0.001484
temperature_celsius            -0.001496
wind_mph                       -0.002942
wind_kph                       -0.003215
air_quality_Nitrogen_dioxide   -0.007295
air_quality_Sulphur_dioxide    -0.009402
air_quality_Carbon_Monoxide    -0.009442
air_quality_PM10               -0.012189
air_quality_PM2.5              -0.012835
air_quality_gb-defra-index     -0.023866
air_quality_us-epa-index       -0.025699
uv_index                       -0.031148
air_quality_Ozone              -0.032924
last_updated_epoch             -0.285076
Name: moon_illumination, dtype: float64

**from weather dataset**

     moon_illumination shows:
        *none of the points are showing correlation as the values are more close to 0